In [2]:
import numpy as np
import gym
import highway_env
from agents.random_agent import RandomAgent
from agents.highway_dqn_agent import DQNAgent

env = gym.make("highway-v0")
# env = gym.make("parking-v0")
# sim_env = gym.make("parking-v0")
# random_agent = RandomAgent(env)
agent = DQNAgent(env)
agent.load_model()

OSError: SavedModel file does not exist at: my_model/{saved_model.pbtxt|saved_model.pb}

In [21]:
env.reset()
done = False
while not done:
    action = random_agent.get_action()
    obs, reward, done, info = env.step(action)
    env.render()

In [20]:
env.action_space

Box(-1.0, 1.0, (2,), float32)

In [19]:
action

array([-0.40664703, -0.03684305], dtype=float32)

In [17]:
np.linalg.norm(obs["achieved_goal"]-obs["desired_goal"]) + reward

1.5091869253908357

In [18]:
obs["desired_goal"]

array([6.000000e-02, 1.400000e-01, 0.000000e+00, 0.000000e+00,
       6.123234e-17, 1.000000e+00])

In [ ]:
obs[]

In [14]:
obs["desired_goal"].shape

(6,)

In [21]:
Q = np.diag([1, 0.3, 0, 0, 0.02, 0.02])
R = np.diag([1, 0.3])

In [23]:
R

array([[1., 0.],
       [0., 1.]])

In [13]:
env.

In [ ]:
obs["achieved_goal"].shape

In [10]:
dir(env)

['PERCEPTION_DISTANCE',
 'REWARD_WEIGHTS',
 'STEERING_RANGE',
 'SUCCESS_GOAL_REWARD',
 '__annotations__',
 '__class__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_automatic_rendering',
 '_cost',
 '_create_road',
 '_create_vehicles',
 '_is_success',
 '_is_terminal',
 '_reset',
 '_reward',
 '_simulate',
 'action_space',
 'action_type',
 'automatic_rendering_callback',
 'call_vehicle_method',
 'change_vehicles',
 'close',
 'compute_reward',
 'config',
 'configure',
 'controlled_vehicles',
 'default_config',
 'define_spaces',
 'done',
 'enable_auto_render',
 'get_available_actions',
 'goal',
 'metadata',
 'np_random',
 'observation_spac

In [11]:
obs['achieved_goal']

array([ 0.10331492, -0.21184659,  0.83636336, -0.55015907, -0.83545377,
        0.54956074])

In [12]:
obs['desired_goal']

array([-2.200000e-01, -1.400000e-01,  0.000000e+00,  0.000000e+00,
        6.123234e-17, -1.000000e+00])

In [3]:
print(obs)

{'observation': array([ 0.10331492, -0.21184659,  0.83636336, -0.55015907, -0.83545377,
        0.54956074]), 'achieved_goal': array([ 0.10331492, -0.21184659,  0.83636336, -0.55015907, -0.83545377,
        0.54956074]), 'desired_goal': array([-2.200000e-01, -1.400000e-01,  0.000000e+00,  0.000000e+00,
        6.123234e-17, -1.000000e+00])}


In [4]:
print(reward)

-0.6265534197230171


In [5]:
print(done)

True


In [6]:
print(action)

[-0.19627972 -0.26177752]
