In [1]:
import numpy as np
import gym
import highway_env
from agents.parking_lqr_agent import LQRAgent

import tensorflow as tf
env = gym.make("parking-v0")
agent = LQRAgent(env)

In [2]:
agent.train(buffer_size=2000, num_epochs=15)

Start of epoch 0
0.001957035856321454
0.002642005681991577
0.002103254199028015
0.0022246495354920626
0.002050539944320917
0.0022687383461743593
0.0023053695913404226
0.0023725624196231365
0.0024916501715779305
0.002328256843611598
0.001968364929780364
0.002344440435990691
0.0015071840025484562
0.0025761444121599197
0.00254037044942379
0.0018051518127322197
0.0023669698275625706
0.0021649000700563192
0.002258240943774581
0.0012867453042417765
0.0021253894083201885
0.0026355735026299953
0.0022795211989432573
0.0028173718601465225
0.001912990352138877
0.0021950015798211098
0.0016280363779515028
0.0021677629556506872
0.002993219066411257
0.002053455449640751
0.00218778382986784
0.001904935110360384
0.0021747732535004616
0.0026813822332769632
0.002061801264062524
0.0014389592688530684
0.002478696871548891
0.0014713048003613949
0.0019007661612704396
0.0022592046298086643
0.001929327379912138
0.0022619254887104034
0.0020860640797764063
0.0023359034676104784
0.002051358809694648
0.00195533619

0.0009492299286648631
0.0010379530722275376
0.0008093603537417948
0.0010881972266361117
Start of epoch 6
0.0010270769707858562
0.0009142488124780357
0.0009563914500176907
0.00122072733938694
0.0007746824994683266
0.0010075605241581798
0.0006474078400060534
0.0010318562854081392
0.0009243251988664269
0.0009367219172418118
0.000961155048571527
0.000816261162981391
0.0010372665710747242
0.0010192450135946274
0.0010338469874113798
0.0007719595450907946
0.000745584606193006
0.0008419507648795843
0.0008583333110436797
0.0009138418245129287
0.0010542813688516617
0.0008113497169688344
0.0009966056095436215
0.0007675375090911984
0.0006852696533314884
0.0010306721087545156
0.0007127244025468826
0.0008587961201556027
0.0011431386228650808
0.00072715018177405
0.0007200951222330332
0.0008251663530245423
0.0011365690734237432
0.0008483136771246791
0.0006515892455354333
0.0008939163526520133
0.0010245642624795437
0.0008039820240810513
0.0008053089259192348
0.0009836319368332624
0.0007116752676665783


0.0005260995822027326
0.0006225307006388903
0.0005315674934536219
0.0005174163379706442
0.0005768133560195565
0.0005278104217723012
0.0006040127482265234
0.0003492160467430949
0.0004301914304960519
0.00044738600263372064
Start of epoch 12
0.0005297506577335298
0.0005443749250844121
0.0003913557156920433
0.00048265658551827073
0.0004808965022675693
0.0005119942943565547
0.00048133949167095125
0.0006021843291819096
0.0004968768917024136
0.0004387258959468454
0.0005077474052086473
0.00036234973231330514
0.0005151660880073905
0.0006103337509557605
0.0005458673695102334
0.0005204190965741873
0.0005213238182477653
0.0005460350075736642
0.000713879126124084
0.0003547716187313199
0.0005221938481554389
0.0004336523124948144
0.0003207448753528297
0.0006168046966195107
0.00042082788422703743
0.0005342940567061305
0.0006799724651500583
0.0006615857710130513
0.00042699859477579594
0.0005981082795187831
0.0004410375258885324
0.0005580387078225613
0.0006492130924016237
0.0005022572004236281
0.0004711

In [3]:
x = env.reset()['observation']
u = env.action_space.sample()
A, B = agent.get_system(x, u)
A, B

(array([[ 0.99733623, -0.08748619, -0.06141737,  0.09496333, -0.04472028,
         -0.12037997],
        [-0.0379949 ,  0.93853966, -0.18534044,  0.03148534, -0.08349883,
          0.0861785 ],
        [ 0.02566931, -0.0552795 ,  1.04314059,  0.13747348, -0.04552839,
          0.20498964],
        [ 0.05453524,  0.05481918,  0.02910703,  0.96718672,  0.04423648,
          0.06074754],
        [ 0.15228349, -0.0881454 , -0.08489006, -0.07790913,  0.91188931,
         -0.06438797],
        [-0.07623054, -0.00199229, -0.04599849,  0.01227362,  0.05789144,
          1.01777388]]),
 array([[ 0.14731456,  0.05221568],
        [-0.02949052,  0.05014031],
        [-0.06308074,  0.04678965],
        [ 0.10200005, -0.13746122],
        [ 0.0861358 ,  0.10232777],
        [ 0.08503238,  0.08581155]]))

In [4]:
x, u

(array([ 0.        ,  0.        , -0.        ,  0.        , -0.9399685 ,
         0.34126122]),
 array([-0.12185476, -0.68230134], dtype=float32))

In [5]:
A @ x + B @ u

array([-0.05262317,  0.07727841,  0.08851231,  0.06051066, -0.95943478,
        0.22399969])

In [6]:
env.step(u)

({'observation': array([ 6.53200774e-05, -4.82975915e-05,  2.29156098e-02, -8.29566916e-03,
         -9.40283738e-01,  3.40391675e-01]),
  'achieved_goal': array([ 6.53200774e-05, -4.82975915e-05,  2.29156098e-02, -8.29566916e-03,
         -9.40283738e-01,  3.40391675e-01]),
  'desired_goal': array([6.000000e-02, 1.400000e-01, 0.000000e+00, 0.000000e+00,
         6.123234e-17, 1.000000e+00])},
 -0.3659877189908109,
 False,
 {'speed': -0.1218547597527504,
  'crashed': False,
  'action': array([-0.12185476, -0.68230134], dtype=float32),
  'is_success': False})

In [10]:
get_action


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



In [11]:
A.round(3)

array([[ 1.002,  0.045, -0.056,  0.009,  0.055,  0.028],
       [ 0.055,  1.021, -0.144, -0.055, -0.002,  0.013],
       [-0.047, -0.013,  1.045,  0.086,  0.243,  0.051],
       [ 0.103,  0.133,  0.059,  1.003, -0.014, -0.062],
       [-0.022,  0.085, -0.016,  0.167,  0.942, -0.03 ],
       [-0.263, -0.158, -0.12 ,  0.046, -0.051,  1.016]])

In [12]:
B.round(3)

array([[ 0.006, -0.071],
       [-0.039, -0.155],
       [ 0.111,  0.085],
       [-0.054,  0.039],
       [-0.079, -0.036],
       [ 0.122, -0.003]], dtype=float32)

In [7]:
a = np.ones((20, 5))
b = np.zeros((20, 3))
c = np.hstack((a, b))
x, y = np.hsplit(c, np.array([5]))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
a is 

True

In [ ]:
tf.expand_dims(x, axis=0), tf.expand_dims(u, axis=0)

In [4]:
agent.get_system(x, u)

TypeError: get_system() takes 2 positional arguments but 3 were given

In [ ]:
np.array([1, 0.3, 0, 0, 0.02, 0.02]) ** 0.5

In [ ]:
x = tf.data.Dataset.from_tensor_slices((np.hstack((a, b)), c))

In [ ]:
y.shape

In [ ]:
for step, (x, y) in enumerate(x.shuffle(200).batch(5)):
    print("hi")

In [ ]:
tf.data.Dataset.from_tensors([np.hstack((a, b)), c])

In [ ]:
def approximate_A(self, x, u, delta=1e-5):
    A = np.zeros((x.shape[0], x.shape[0]))
    for i in range(A.shape[1]):

        x_perturbed = x.copy()
        x_perturbed[i] -= delta

        pert_neg = self.simulate_dynamics(x_perturbed, u)

        x_perturbed = x.copy()
        x_perturbed[i] += delta
        pert_pos = self.simulate_dynamics(x_perturbed, u)

        A[:,i] = (pert_pos-pert_neg) / (2*delta)

    return A

In [ ]:
env.observation_space["desired_goal"].n

In [ ]:
env.action_space.shape

In [ ]:
x, u, x_next = buffer[0]

In [ ]:
data = list(map(list, zip(*buffer)))
x_lst = np.array(data[0])
u_lst = np.array(data[1])
x_next_lst = np.array(data[2])

In [ ]:
np.hstack((u_lst, x_lst)).shape

In [ ]:
a, b = np.hsplit(np.hstack((u_lst, x_lst)), np.array([2]))

In [ ]:
a.shape

In [ ]:
b.shape

In [ ]:
np.hstack((u_lst, x_lst))

In [ ]:
AB, _, _, _ = np.linalg.lstsq(np.hstack((x_lst, u_lst)),
                             x_next_lst)
AB.round(5)
A = AB[:6, ]
B = AB[:2, ]

In [ ]:
B.shape

In [ ]:
x @ A + u @ B 

In [ ]:
x_next

In [ ]:
y, _, _, _ = np.linalg.lstsq(np.hstack((u_lst, x_lst))[:150],
                             x_next_lst[:150])
y.round(2)

In [ ]:
np.array(x_lst).shape

In [ ]:
np.linalg.solve(a, b)